//this source code was auto-generated by LuHaxe, do not modify it

package;
extern class Debugger
{
	static var useLog:Bool;
	static var threadStack:String;
	static var logger:ILogger;
	static var useLog:Bool;
	static var threadStack:String;
	static var logger:ILogger;
}

