//this source code was auto-generated by LuHaxe, do not modify it

package;
extern class LuaProfiler
{
	static var list:List`1;
	static var list:List`1;
	static function Clear():Void;
	static function GetID(name:String):Int32;
	static function BeginSample(id:Int32):Void;
	static function EndSample():Void;
}

